# Note: This workflow requires some secrets setup, and set on this repo with the names:
# 'MMEX_PUBLISH_TOKEN' (A GitHub Personal Access Token with appropriate permissions - for publishing the built artifacts)
# 'APPLEID' (The username of your Apple developer account - for notarizing the mac artifacts)
# 'APPLEID_PASSWORD' (An app-specific password - for notarizing the mac artifacts)
# 'CSC_LINK' (The HTTPS link or local path to certificate - for code signing of mac artifacts)
# 'CSC_KEY_PASSWORD' (The password to decrypt the certificate given in CSC_LINK - for code signing of mac artifacts)
# 'WIN_CSC_LINK' (The HTTPS link or local path to certificate - for code signing of windows artifacts)
# 'WIN_CSC_KEY_PASSWORD' (The password to decrypt the certificate given in CSC_LINK - for code signing of windows artifacts)

name: Build and publish MMEX releases
on:
    push:
        tags:
            - "v*"
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest, windows-latest, macos-latest ]
        env:
            CCACHE_DIR: ${{ github.workspace }}/.ccache
        steps:
            -   name: Check out
                uses: actions/checkout@v2
                with:
                    submodules: 'recursive'

            -   name: (${{runner.os}}) Install important software
                if: runner.os == 'Linux'
                run: |
                    sudo apt-key adv --fetch-keys https://repos.codelite.org/CodeLite.asc
                    sudo apt-add-repository 'deb https://repos.codelite.org/wx3.1.5/ubuntu/ focal universe'
                    sudo apt-get update
                    sudo apt-get install -y --no-install-recommends \
                        ccache \
                        clang \
                        cmake \
                        gettext \
                        libcurl4-openssl-dev \
                        liblua5.3-dev \
                        libwxgtk3.1unofficial-dev \
                        rapidjson-dev \

            -   name: (${{runner.os}}) Install important software
                if: runner.os == 'macOS'
                run: |
                    brew install ccache wxwidgets
                    ln -s $(which ccache) ./ccache

            -   name: (${{runner.os}}) Install important software
                if: runner.os == 'Windows'
                run: |
                    choco install -y ccache cmake curl nsis wxwidgets

            -   name: Set up ccache
                run: |
                    mkdir ./.ccache
                    ccache -o compiler_check='%compiler% -dumpmachine; %compiler% -dumpversion'

            -   name: (${{runner.os}}) Set up C++ Compiler
                if: runner.os == 'Linux'
                run: |
                    sudo update-alternatives --set cc /usr/bin/clang
                    sudo update-alternatives --set c++ /usr/bin/clang++

            -   name: Cache build cache
                uses: actions/cache@v2
                with:
                    path: |
                        ${{ github.workspace }}/.ccache
                    key: ${{ runner.os }}-build-cache-${{ github.repository }}
                    restore-keys: ${{ runner.os }}-build-cache-

            -   name: (${{runner.os}}) Build release
                if: runner.os == 'Linux'
                run: |
                    mkdir build
                    cd build
                    export MAKEFLAGS=-j
                    cmake \
                        -DCMAKE_BUILD_TYPE=Release \
                        ..
                    cmake --build . --target package

            -   name: (${{runner.os}}) Build release
                if: runner.os == 'macOS'
                run: |
                    mkdir build
                    cd build
                    export MAKEFLAGS=-j
                    cmake -DCMAKE_CXX_FLAGS="-w" \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DMACOSX_DEPLOYMENT_TARGET=10.15 \
                        ..
                    cmake --build . --target package

            -   name: (${{runner.os}}) Build release
                if: runner.os == 'Windows'
                run: |
                    mkdir build
                    cd build
                    set "CL=/MP"
                    cmake -G "Visual Studio 16 2019 Win64" --build .. --target install --config Release /maxcpucount /verbosity:minimal /nologo /p:PreferredToolArchitecture=x64
                    cpack .

            -   name: (${{runner.os}}) Show release
                if: runner.os == 'Linux' || runner.os == 'macOS'
                run: |
                    echo "ls -lha"
                    ls -lha
                    echo "ls -lha build"
                    ls -lha build

            -   name: (${{runner.os}}) Show release
                if: runner.os == 'Windows'
                run: |
                    echo "dir"
                    dir
                    echo "dir build"
                    dir build





            # Only upload artifacts built on Linux
            -   name: Upload build artifact
                if: runner.os == 'Linuxx' # broken to avoid execution
                uses: actions/upload-artifact@v2
                with:
                    name: ${{ github.sha }}
                    path: out
